//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWascar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_venta
    {
        public int Iddetalle_venta { get; set; }
        public Nullable<int> Idventa { get; set; }
        public Nullable<int> Iddetalle_ingreso { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio_venta { get; set; }
        public Nullable<decimal> Descuento { get; set; }
    }
}
