//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWascar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Idventa { get; set; }
        public Nullable<int> Idcliente { get; set; }
        public Nullable<int> Idtrabajador { get; set; }
        public Nullable<System.DateTime> Fecha_venta { get; set; }
        public string Tipo_comprobante { get; set; }
        public string Serie_comprobante { get; set; }
        public string Correlativo { get; set; }
        public Nullable<decimal> Itbis { get; set; }
    }
}
